review suggestions

diff --git a/.github/workflows/setup/action.yaml b/.github/workflows/setup/action.yaml
--- a/.github/workflows/setup/action.yaml
+++ b/.github/workflows/setup/action.yaml
@@ -1,36 +1,62 @@
-name: 'openpilot env setup, with retry on failure'
+name: 'openpilot env setup'
 
 inputs:
   git_lfs:
     description: 'Whether or not to pull the git lfs'
     required: false
     default: 'true'
-
-env:
-  SLEEP_TIME: 30 # Time to sleep between retries
+  is_retried:
+    description: 'A mock param that asserts that we use the setup-with-retry instead of this action directly'
+    required: false
+    default: 'false'
 
 runs:
   using: "composite"
   steps:
-    - id: setup1
-      uses: ./.github/workflows/base_setup
-      continue-on-error: true
-      with:
-        git_lfs: ${{ inputs.git_lfs }}
-    - if: steps.setup1.outcome == 'failure'
+    # assert that this action is retried using the setup-with-retry
+    - shell: bash
+      if: ${{ inputs.is_retried == 'false' }}
+      run: |
+        echo "You should not run this action directly. Use setup-with-retry instead"
+        exit 1
+
+    # do this after checkout to ensure our custom LFS config is used to pull from GitLab
+    - shell: bash
+      if: ${{ inputs.git_lfs == 'true' }}
+      run: git lfs pull
+
+    # build cache
+    - id: date
       shell: bash
-      run: sleep ${{ env.SLEEP_TIME }}
-    - id: setup2
-      if: steps.setup1.outcome == 'failure'
-      uses: ./.github/workflows/base_setup
-      continue-on-error: true
+      run: echo "CACHE_COMMIT_DATE=$(git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV
+    - shell: bash
+      run: echo "$CACHE_COMMIT_DATE"
+    - id: restore-scons-cache
+      uses: actions/cache/restore@v3
       with:
-        git_lfs: ${{ inputs.git_lfs }}
-    - if: steps.setup2.outcome == 'failure'
+        path: .ci_cache/scons_cache
+        key: scons-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
+        restore-keys: |
+          scons-${{ env.CACHE_COMMIT_DATE }}-
+          scons-
+    # if we didn't get a cache hit, make the directory manually so it doesn't fail on future steps
+    - id: scons-cache-setup
       shell: bash
-      run: sleep ${{ env.SLEEP_TIME }}
-    - id: setup3
-      if: steps.setup2.outcome == 'failure'
-      uses: ./.github/workflows/base_setup
+      if: steps.restore-scons-cache.outputs.cache-hit != 'true'
+      run: mkdir -p $GITHUB_WORKSPACE/.ci_cache/scons_cache
+    # as suggested here: https://github.com/moby/moby/issues/32816#issuecomment-910030001
+    - id: normalize-file-permissions
+      shell: bash
+      name: Normalize file permissions to ensure a consistent docker build cache
+      run: |
+        find . -type f -executable -not -perm 755 -exec chmod 755 {} \;
+        find . -type f -not -executable -not -perm 644 -exec chmod 644 {} \;
+    - id: setup-buildx-action
+      if: contains(runner.name, 'buildjet')
+      name: Set up Docker Buildx on buildjet to ensure a consistent cache
+      uses: docker/setup-buildx-action@v2
       with:
-        git_lfs: ${{ inputs.git_lfs }}
+        driver: docker-container
+    # build our docker image
+    - shell: bash
+      run: eval ${{ env.BUILD }}
