revert action

diff --git a/.github/workflows/setup/action.yaml b/.github/workflows/setup/action.yaml
--- a/.github/workflows/setup/action.yaml
+++ b/.github/workflows/setup/action.yaml
@@ -10,58 +10,54 @@ inputs:
     required: false
     default: 'false'
 
-  runs:
-    using: "composite"
-    steps:
-      # Verify if the setup is retried using setup-with-retry
-      - name: Verify Retry Setup
-        shell: bash
-        if: ${{ inputs.is_retried == 'false' }}
-        run: |
-          echo "This action should not run directly. Use setup-with-retry instead."
-          exit 1
+runs:
+  using: "composite"
+  steps:
+    # assert that this action is retried using the setup-with-retry
+    - shell: bash
+      if: ${{ inputs.is_retried == 'false' }}
+      run: |
+        echo "You should not run this action directly. Use setup-with-retry instead"
+        exit 1
 
-      # Perform git lfs pull if necessary, ensure condition checks for files existence
-      - name: Git LFS Pull
-        shell: bash
-        run: git lfs pull
-        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
+    # do this after checkout to ensure our custom LFS config is used to pull from GitLab
+    - shell: bash
+      run: git lfs pull
 
-      # Login to Docker Hub to avoid rate limiting on BuildJet
-      - name: Login to Docker Hub
-        shell: bash
-        if: ${{ contains(runner.name, 'buildjet') }}
-        run: |
-          if [ -z "${{ inputs.docker_hub_pat }}" ]; then
-            echo "Docker Hub PAT is required."
-            exit 1
-          fi
-          docker login -u adeebshihadeh -p ${{ inputs.docker_hub_pat }}
+    # on BuildJet runners, must be logged into DockerHub to avoid rate limiting
+    # https://buildjet.com/for-github-actions/docs/guides/docker
+    - shell: bash
+      if: ${{ contains(runner.name, 'buildjet') && inputs.docker_hub_pat == '' }}
+      run: |
+        echo "Need to set the Docker Hub PAT secret as an input to this action"
+        exit 1
+    - name: Login to Docker Hub
+      if: contains(runner.name, 'buildjet')
+      shell: bash
+      run: |
+        docker login -u adeebshihadeh -p ${{ inputs.docker_hub_pat }}
 
-      # Set up caching for faster builds, using more specific keys and restoration logic
-      - name: Set Cache Dates
-        shell: bash
-        run: echo "CACHE_COMMIT_DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
-
-      - name: Restore Build Cache
-        uses: actions/cache@v2
-        with:
-          path: .ci_cache/scons_cache
-          key: ${{ runner.os }}-scons-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-scons-${{ env.CACHE_COMMIT_DATE }}
-            ${{ runner.os }}-scons-
-
-      # Normalize file permissions to ensure a consistent Docker build cache
-      - name: Normalize File Permissions
-        shell: bash
-        run: |
-          find . -type f -executable -not -perm 755 -exec chmod 755 {} \;
-          find . -type f -not -executable -not -perm 644 -exec chmod 644 {} \;
-
-      # Build Docker image
-      - name: Build Docker Image
-        shell: bash
-        run: eval ${{ env.BUILD }}
-        env:
-          BUILD: docker build -t openpilot-env .
+    # build cache
+    - id: date
+      shell: bash
+      run: echo "CACHE_COMMIT_DATE=$(git log -1 --pretty='format:%cd' --date=format:'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV
+    - shell: bash
+      run: echo "$CACHE_COMMIT_DATE"
+    - id: scons-cache
+      uses: ./.github/workflows/auto-cache
+      with:
+        path: .ci_cache/scons_cache
+        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
+        restore-keys: |
+          scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}
+          scons-${{ runner.arch }}
+    # as suggested here: https://github.com/moby/moby/issues/32816#issuecomment-910030001
+    - id: normalize-file-permissions
+      shell: bash
+      name: Normalize file permissions to ensure a consistent docker build cache
+      run: |
+        find . -type f -executable -not -perm 755 -exec chmod 755 {} \;
+        find . -type f -not -executable -not -perm 644 -exec chmod 644 {} \;
+    # build our docker image
+    - shell: bash
+      run: eval ${{ env.BUILD }}
