try removing stuff

diff --git a/.github/workflows/setup/action.yaml b/.github/workflows/setup/action.yaml
--- a/.github/workflows/setup/action.yaml
+++ b/.github/workflows/setup/action.yaml
@@ -27,6 +27,15 @@ runs:
       run: |
         echo "You should not run this action directly. Use setup-with-retry instead"
         exit 1
+    
+    # cleanup some unused directories to save on space
+    # https://stackoverflow.com/questions/75536771/github-runner-out-of-disk-space-after-building-docker-image
+    - shell: bash
+      run: |
+        sudo rm -rf \
+          /usr/share/dotnet /usr/local/lib/android /opt/ghc \
+          /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
+          /usr/lib/jvm || true
 
     # do this after checkout to ensure our custom LFS config is used to pull from GitLab
     - shell: bash
