Removed numpy_fast and updated dependent files to eliminate dependency

diff --git a/scripts/post-commit b/scripts/post-commit
--- a/scripts/post-commit
+++ b/scripts/post-commit
@@ -1,7 +1,3 @@
-#!/usr/bin/env bash
-set -e
-if [[ -f .git/hooks/post-commit.d/post-commit ]]; then
-  .git/hooks/post-commit.d/post-commit
-fi
-tools/op.sh lint --fast
-echo ""
+#!/bin/sh
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
+git lfs post-commit "$@"
