docs with unit_test

diff --git a/.github/workflows/docs.yaml b/.github/workflows/docs.yaml
--- a/.github/workflows/docs.yaml
+++ b/.github/workflows/docs.yaml
@@ -29,7 +29,17 @@ jobs:
     - uses: ./.github/workflows/setup-with-retry
     - name: Build openpilot
       run: |
-        ${{ env.RUN }} "scons -j$(nproc)"
+        {
+        echo 'BUILD_LOG<<EOF'
+        echo $(${{ env.RUN }} "scons -j$(nproc) --cache-show")
+        echo EOF
+        } >> $GITHUB_OUTPUT
+      id: build_openpilot
+    - name: unit test - if cached by abspath
+      if: contains(${{ steps.build_openpilot.outputs.BUILD_LOG }}, ${{ env.WORKSPACE }})
+      run:
+        echo "Failed - contains abspath while building"
+        exit 1
     - name: Build docs
       run: |
         ${{ env.RUN }} "apt update && apt install -y doxygen && cd docs && make -j$(nproc) html"
