reduce diff

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -19,30 +19,166 @@ env:
       docker build --cache-from docker.io/commaai/openpilotci:latest -t tmppilot -f Dockerfile.openpilotci .
 
 jobs:
-  #build_mac:
-  #  name: build macos
-  #  runs-on: macos-10.15
-  #  timeout-minutes: 60
-  #  steps:
-  #  - uses: actions/checkout@v2
-  #    with:
-  #      submodules: true
-  #  - name: Cache dependencies
-  #    id: dependency-cache
-  #    uses: actions/cache@v2
-  #    with:
-  #      path: |
-  #        ~/.pyenv
-  #        ~/Library/Caches/pip
-  #        ~/Library/Caches/pipenv
-  #        ~/Library/Caches/Homebrew
-  #      key: ${{ hashFiles('tools/mac_setup.sh') }}
-  #  - name: Install dependencies
-  #    run: ./tools/mac_setup.sh
-  #  - name: Build openpilot
-  #    run: eval "$(pyenv init -)" && scons -j$(nproc)
-  #  - name: Brew cleanup
-  #    run: brew cleanup || true # keeps our cache small
+  build_release:
+    name: build release
+    runs-on: ubuntu-16.04
+    timeout-minutes: 50
+    env:
+      TEST_DIR: tmppilot
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        submodules: true
+    - name: Strip non-release files
+      run: |
+        mkdir $TEST_DIR
+        cp -pR --parents $(cat release/files_common) $TEST_DIR
+        cp Dockerfile.openpilot_base Dockerfile.openpilotci $TEST_DIR
+        # need this to build on x86
+        cp -pR --parents phonelibs/libyuv phonelibs/snpe \
+                          external/bin selfdrive/modeld/runners $TEST_DIR
+        # need these so docker copy won't fail
+        cp Pipfile Pipfile.lock .pylintrc .pre-commit-config.yaml $TEST_DIR
+        cd $TEST_DIR
+        mkdir laika laika_repo tools
+    - name: Build Docker image
+      run: cd $TEST_DIR && eval "$BUILD"
+    - name: Build openpilot and run quick check
+      run: |
+          $RUN "cd /tmp/openpilot && \
+                scons -j$(nproc) && \
+                $UNIT_TEST selfdrive/car"
+
+  build_mac:
+    name: build macos
+    runs-on: macos-10.15
+    timeout-minutes: 60
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        submodules: true
+    - name: Cache dependencies
+      id: dependency-cache
+      uses: actions/cache@v2
+      with:
+        path: |
+          ~/.pyenv
+          ~/Library/Caches/pip
+          ~/Library/Caches/pipenv
+          ~/Library/Caches/Homebrew
+        key: ${{ hashFiles('tools/mac_setup.sh') }}
+    - name: Install dependencies
+      run: ./tools/mac_setup.sh
+    - name: Build openpilot
+      run: eval "$(pyenv init -)" && scons -j$(nproc)
+    - name: Brew cleanup
+      run: brew cleanup || true # keeps our cache small
+
+  build_webcam:
+    name: build webcam
+    runs-on: ubuntu-16.04
+    timeout-minutes: 90
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        submodules: true
+    - name: Build Docker image
+      run: |
+        docker pull docker.io/commaai/openpilotwebcamci:latest
+        docker build --cache-from docker.io/commaai/openpilotwebcamci:latest -t tmppilotwebcam -f tools/webcam/Dockerfile .
+    - name: Build openpilot
+      run: docker run --shm-size 1G --rm tmppilotwebcam /bin/sh -c "cd /tmp/openpilot && USE_WEBCAM=1 scons -j$(nproc)"
+    - name: Push to dockerhub
+      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'commaai/openpilot'
+      run: |
+          docker login -u wmelching -p ${{ secrets.COMMA_DOCKERHUB_TOKEN}}
+          docker tag tmppilotwebcam docker.io/commaai/openpilotwebcamci:latest
+          docker push docker.io/commaai/openpilotwebcamci:latest
+
+  docker_push:
+    name: docker push
+    runs-on: ubuntu-16.04
+    timeout-minutes: 50
+    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.repository == 'commaai/openpilot'
+    needs: static_analysis # hack to ensure slow tests run first since this and static_analysis are fast
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: true
+      - name: Build Docker image
+        run: eval "$BUILD"
+      - name: Push to dockerhub
+        run: |
+          docker login -u wmelching -p ${{ secrets.COMMA_DOCKERHUB_TOKEN}}
+          docker tag commaai/openpilot-base:latest docker.io/commaai/openpilot-base:latest
+          docker push docker.io/commaai/openpilot-base:latest
+          docker tag tmppilot docker.io/commaai/openpilotci:latest
+          docker push docker.io/commaai/openpilotci:latest
+
+  docker_push_prebuilt:
+    name: docker push prebuilt
+    runs-on: ubuntu-16.04
+    timeout-minutes: 50
+    if: github.event_name == 'status' && github.repository == 'commaai/openpilot'
+    needs: [static_analysis, unit_tests, process_replay, test_longitudinal, test_car_models]
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: true
+      - name: Build Docker image
+        run: echo "RUN cd /tmp/openpilot && scons -c && scons -j\$(nproc)" >> Dockerfile.openpilotci && eval "$BUILD"
+      - name: Push to dockerhub
+        run: |
+          docker login -u wmelching -p ${{ secrets.COMMA_DOCKERHUB_TOKEN}}
+          docker tag tmppilot docker.io/commaai/openpilot:latest
+          docker push docker.io/commaai/openpilot:latest
+
+  static_analysis:
+    name: static analysis
+    runs-on: ubuntu-16.04
+    timeout-minutes: 50
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: true
+      - name: Build Docker image
+        run: eval "$BUILD"
+      - name: pre-commit
+        run: $RUN "cd /tmp/openpilot/ && git init && git add -A && pre-commit run --all"
+
+  valgrind:
+    name: valgrind
+    runs-on: ubuntu-16.04
+    timeout-minutes: 50
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: true
+      - name: Cache dependencies
+        id: dependency-cache
+        uses: actions/cache@v2
+        with:
+          path: |
+            /tmp/comma_download_cache
+          key: ${{ hashFiles('.github/workflows/test.yaml', 'selfdrive/test/test_valgrind_replay.py') }}
+      - name: Build Docker image
+        run: eval "$BUILD"
+      - name: Run valgrind
+        run: |
+          $PERSIST_WITH_CACHE "cd /tmp/openpilot && \
+                    scons -j$(nproc) && \
+                    FILEREADER_CACHE=1 python selfdrive/test/test_valgrind_replay.py"
+      - name: Print logs
+        if: always()
+        run: |
+          docker cp tmppilot:/tmp/openpilot/selfdrive/test/valgrind_logs.txt valgrind_logs.txt
+          cat valgrind_logs.txt
+      - uses: actions/upload-artifact@v2
+        if: always()
+        continue-on-error: true
+        with:
+          name: valgrind_logs.txt
+          path: valgrind_logs.txt
 
   unit_tests:
     name: unit tests
