TEMP: disable more

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -63,14 +63,15 @@ jobs:
           ~/.pyenv
           ~/Library/Caches/pip
           ~/Library/Caches/pipenv
-          /usr/local
+          ~/Library/Caches/Homebrew
+          /usr/local/Homebrew
         key: ${{ hashFiles('tools/mac_setup.sh') }}
     - name: Install dependencies
       run: ./tools/mac_setup.sh
-    - name: Build openpilot
-      run: eval "$(pyenv init -)" && scons -j$(nproc)
-    - name: Brew cleanup
-      run: brew cleanup || true # keeps our cache small
+    # - name: Build openpilot
+    #   run: eval "$(pyenv init -)" && scons -j$(nproc)
+    # - name: Brew cleanup
+    #   run: brew cleanup || true # keeps our cache small
 
   build_webcam:
     name: build webcam
